language: elixir
elixir:
  - 1.10.4
otp_release:
  - 23.0
services:
  - postgresql
addons:
  postgresql: "12"
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12
      - postgresql-server-dev-12