language: elixir
elixir:
  - 1.10.4
otp_release:
  - 23.0
services:
  - postgresql
addons:
  postgresql: "12"
  apt:
    packages:
      - postgresql-12
      - postgresql-client-12
      - postgresql-server-dev-12
before_install:
  - sudo sed -i 's/port = 5433/port = 5432/' /etc/postgresql/12/main/postgresql.conf
  - sudo cp /etc/postgresql/{9.3,12}/main/pg_hba.conf
  - sudo pg_ctlcluster 12 main restart