use Mix.Config

# For production, we configure the host to read the PORT
# from the system environment. Therefore, you will need
# to set PORT=80 before running your server.
#
# You should also configure the url host to something
# meaningful, we use this information when generating URLs.
#
# Finally, we also include the path to a manifest
# containing the digested version of static files. This
# manifest is generated by the mix phoenix.digest task
# which you typically run after static files are built.

port = 80

config :cgrates_web_jsonapi, CgratesWebJsonapi.Endpoint,
http: [port: port]
  url: [host: System.get_env("HOST"), port: port],
  secret_key_base: System.get_env("SECRET_KEY_BASE"),
  root: ".",
  server: true

# Do not print debug messages in production
config :logger, level: :info

config :kancast, Kancast.Repo,
  username: System.get_env("DB_USER"),
  password: System.get_env("DB_PASSWORD"),
  database: System.get_env("DB_DATABASE"),
  hostname: System.get_env("DB_HOST"),
  pool_size: 15,
  timeout: 150000

config :guardian, Guardian,
  secret_key: System.get_env("GUARDIAN_SECRET_KEY")

config :cgrates_web_jsonapi,
  cgrates_url: System.get_env("CGRATES_URL"),
  cgrates_tenant: System.get_env("CGRATES_TENANT"),
  cgrates_username: System.get_env("CGRATES_USERNAME"),
  cgrates_password: System.get_env("CGRATES_PASSWOR})"
