use Mix.Config

# For production, we configure the host to read the PORT
# from the system environment. Therefore, you will need
# to set PORT=80 before running your server.
#
# You should also configure the url host to something
# meaningful, we use this information when generating URLs.
#
# Finally, we also include the path to a manifest
# containing the digested version of static files. This
# manifest is generated by the mix phoenix.digest task
# which you typically run after static files are built.
config :cgrates_web_jsonapi, CgratesWebJsonapi.Endpoint,
  http: [port: {:system, "PORT"}],
  url: [host: "${HOST}", port: 80],
  secret_key_base: "${SECRET_KEY_BASE}",
  root: ".",
  server: true

# Do not print debug messages in production
config :logger, level: :info

config :cgrates_web_jsonapi, CgratesWebJsonapi.Repo,
  adapter: Ecto.Adapters.Postgres,
  username: "${POSTGRES_USER}",
  password: "${POSTGRES_PASSWORD}",
  database: "${POSTGRES_DATABASE}",
  hostname: "${POSTGRES_HOST}",
  pool_size: 10

config :guardian, Guardian,
  secret_key: "${GUARDIAN_SECRET_KEY}"

config :cgrates_web_jsonapi,
  cgrates_url: "${CGRATES_URL}",
  cgrates_tenant: "${CGRATES_TENANT}",
  cgrates_username: "${CGRATES_USERNAME}",
  cgrates_password: "${CGRATES_PASSWORD}"
